[package]
name = "scientific-workflow-macros"
version = "0.2.1"
edition = "2024"
rust-version = "1.97"
authors = ["Dingyi Sun"]
description = "Declaration macros for scientific-workflow"
license = "MIT"
repository = "https://github.com/dingyisun0101/Scientific-Workflow"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
